name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.1.0, 5.2.0, 6.0.0, 6.1.0, master]
        ruby_version: [3.0, 2.7, 2.6, 2.5]
        exclude:
          - ruby_version: 2.5
            rails_version: master
          - ruby_version: 2.6
            rails_version: master
          - ruby_version: 3.0
            rails_version: 5.1.0
          - ruby_version: 3.0
            rails_version: 5.2.0

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Run test
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      run: |
        bundle update
        bundle exec rake
